# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([( name: 'Star Wars' ), ( name: 'Lord of the Rings' )])
#   Character.create(name: 'Luke', movie: movies.first)

Option.destroy_all
Question.destroy_all
SurveyFormat.destroy_all
Employee.destroy_all
Company.destroy_all

@facebook = Company.create!(company_name: 'Facebook')
@employee = Employee.create!(username: 'admin', first_name: 'John', last_name: 'Doe', email: 'admin@gmail.com', date_of_birth: '1994-02-03', company_id: @facebook.id, password: '123456')

puts "#{Company.count} companies created"
puts "#{Employee.count} employee created"

@Demographics = SurveyFormat.create!(survey_name: "Employee Demographics")
@IMS = SurveyFormat.create!(survey_name: "IMS - Internal Motivation to Respond without Prejudice")
@EMS = SurveyFormat.create!(survey_name: "EMS - External Motivation to Respond without Prejduice")
@MP = SurveyFormat.create!(survey_name: "MP - Motivation to Respond with Prejudice")
@IAT = SurveyFormat.create!(survey_name: "IAT - Implicit Aptitude Test")
@Shoulds_Woulds = SurveyFormat.create!(survey_name: "Shoulds/Woulds Assessment")
@Modern_Racism_2000 = SurveyFormat.create!(survey_name: "Modern Racism 2000 Scale")
@Sublte_Blatant = SurveyFormat.create!(survey_name: "Subtle/Blatant Racism Scale")
@Organizational_Inclusivity_Audit = SurveyFormat.create!(survey_name: "Organizational Inclusivity Audit")
@Concern = SurveyFormat.create!(survey_name: "Concern for Prejudice")
@Priming = SurveyFormat.create!(survey_name: "Priming")
@SR_Questionnaire = SurveyFormat.create!(survey_name: "Self-Regulation Questionnaire")
@SR_Journal = SurveyFormat.create!(survey_name: "Self-Regulation Strategy Journal")

puts "#{SurveyFormat.count} survey formats created"

@Q0 = Question.create!(survey_format_id: @Demographics.id, question_format: "multiple-choice", question_category: "demographics", question_copy: "What is your age?")
@Q1 = Question.create!(survey_format_id: @Demographics.id, question_format: "multiple-choice", question_category: "demographics", question_copy: "What is your gender?")
@Q2 = Question.create!(survey_format_id: @Demographics.id, question_format: "multiple-choice", question_category: "demographics", question_copy: "Do you identify as transgender?")
@Q3 = Question.create!(survey_format_id: @Demographics.id, question_format: "multiple-choice", question_category: "demographics", question_copy: "Do you identify as a member of the LGBT+ community?")
@Q4 = Question.create!(survey_format_id: @Demographics.id, question_format: "multiple-choice", question_category: "demographics", question_copy: "What is your sexual orientation?")
@Q5 = Question.create!(survey_format_id: @Demographics.id, question_format: "select all that apply", question_category: "demographics", question_copy: "What racial/ethnic category do you identify with?")

  Option.create!(question_id: @Q0.id, scoring_value: 1, option_copy: "18-24")
  Option.create!(question_id: @Q0.id, scoring_value: 1, option_copy: "25-34")
  Option.create!(question_id: @Q0.id, scoring_value: 1, option_copy: "35-44")
  Option.create!(question_id: @Q0.id, scoring_value: 1, option_copy: "45-54")
  Option.create!(question_id: @Q0.id, scoring_value: 1, option_copy: "55-64")
  Option.create!(question_id: @Q0.id, scoring_value: 1, option_copy: "65+")
  Option.create!(question_id: @Q1.id, scoring_value: 1, option_copy: "Male")
  Option.create!(question_id: @Q1.id, scoring_value: 1, option_copy: "Female")
  Option.create!(question_id: @Q1.id, scoring_value: 1, option_copy: "Non-Binary")
  Option.create!(question_id: @Q1.id, scoring_value: 1, option_copy: "Prefer Not to Say")
  Option.create!(question_id: @Q1.id, scoring_value: 1, option_copy: "Other")
  Option.create!(question_id: @Q1.id, scoring_value: 1, option_copy: "Prefer to Self-Describe:")
  Option.create!(question_id: @Q2.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q2.id, scoring_value: 1, option_copy: "No")
  Option.create!(question_id: @Q2.id, scoring_value: 1, option_copy: "Prefer Not to Say")
  Option.create!(question_id: @Q3.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q3.id, scoring_value: 1, option_copy: "No")
  Option.create!(question_id: @Q3.id, scoring_value: 1, option_copy: "No but I identify as an Ally")
  Option.create!(question_id: @Q3.id, scoring_value: 1, option_copy: "Prefer Not to Say")
  Option.create!(question_id: @Q4.id, scoring_value: 1, option_copy: "Straight/Heterosexual")
  Option.create!(question_id: @Q4.id, scoring_value: 1, option_copy: "Gay/Lesbian")
  Option.create!(question_id: @Q4.id, scoring_value: 1, option_copy: "Bisexual")
  Option.create!(question_id: @Q4.id, scoring_value: 1, option_copy: "Queer")
  Option.create!(question_id: @Q4.id, scoring_value: 1, option_copy: "Other")
  Option.create!(question_id: @Q4.id, scoring_value: 1, option_copy: "Prefer to Self-Describe:")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "African-American/Black")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Native American/Alaska Native")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "East Asian")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Hispanic/LatinX")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Middle Eastern")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Pacific Islander")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "South Asian")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Southeast Asian")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "White/Caucasian")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Other")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "Prefer to Self-Describe:")
  Option.create!(question_id: @Q5.id, scoring_value: 1, option_copy: "None of the Above")

@Q7 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "boolean", question_category: "stereotype replacement", question_copy: "Since your last journal, have you used the STEREOTYPE REPLACEMENT strategy?")
@Q8 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "free-response", question_category: "stereotype replacement", question_copy: "If so, please describe a situation in which STEREOTYPE REPLACEMENT was used?")
@Q9 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "boolean", question_category: "counter stereotype imaging", question_copy: "Since your last journal, have you used the COUNTER STEREOTYPE IMAGING strategy?")
@Q10 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "free-response", question_category: "counter stereotype imaging", question_copy: "If so, please describe a situation in which COUNTER STEREOTYPE IMAGING was used?")
@Q11 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "boolean", question_category: "individualizing", question_copy: "Since your last journal, have you used the INDIVIDUALIZING strategy?")
@Q12 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "free-response", question_category: "individualizing", question_copy: "If so, please describe a situation in which INDIVIDUALIZING 
was used?")
@Q13 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "boolean", question_category: "perspective-taking", question_copy: "Since your last journal, have you used the PERSPECTIVE-TAKING strategy?")
@Q14 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "free-response", question_category: "perspective-taking", question_copy: "If so, please describe a situation in which PERSPECTIVE-TAKING
was used?")
@Q15 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "boolean", question_category: "contact", question_copy: "Since your last journal, have you used the CONTACT strategy?")
@Q16 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "free-response", question_category: "contact", question_copy: "If so, please describe a situation in which CONTACT was used?")
@Q17 = Question.create!(survey_format_id: @SR_Journal.id, question_format: "free-response", question_copy: "You may provide general feedback regarding the prejudice-reduction strategies in the space below.")

  Option.create!(question_id: @Q7.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q7.id, scoring_value: 0, option_copy: "No")
  Option.create!(question_id: @Q9.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q9.id, scoring_value: 0, option_copy: "No")
  Option.create!(question_id: @Q11.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q11.id, scoring_value: 0, option_copy: "No")
  Option.create!(question_id: @Q13.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q13.id, scoring_value: 0, option_copy: "No")
  Option.create!(question_id: @Q15.id, scoring_value: 1, option_copy: "Yes")
  Option.create!(question_id: @Q15.id, scoring_value: 0, option_copy: "No")

@Q18 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "stereotype replacement", question_copy: "Perceived Likelihood of Using" )
@Q19 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "stereotype replacement", question_copy: "Willingness to Use" )
@Q20 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "stereotype replacement", question_copy: "Perceived Difficulty")
@Q21 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "stereotype replacement", question_copy: "Perceived Effectiveness" )
@Q22 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "stereotype replacement", question_copy: "Perceived Frequency of Opportunity to Use" )

  Option.create!(question_id: @Q18.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q18.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q18.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q18.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q18.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q18.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q18.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q19.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q19.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q19.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q19.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q19.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q19.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q19.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q20.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q20.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q20.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q20.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q20.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q20.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q20.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q21.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q21.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q21.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q21.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q21.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q21.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q21.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q22.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q22.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q22.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q22.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q22.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q22.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q22.id, scoring_value: 7, option_copy: "Very Much" )

@Q23 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "counter stereotype imaging", question_copy: "Perceived Likelihood of Using" )
@Q24 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "counter stereotype imaging", question_copy: "Willingness to Use" )
@Q25 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "counter stereotype imaging", question_copy: "Perceived Difficulty")
@Q26 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "counter stereotype imaging", question_copy: "Perceived Effectiveness" )
@Q27 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "counter stereotype imaging", question_copy: "Perceived Frequency of Opportunity to Use" )

  Option.create!(question_id: @Q23.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q23.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q23.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q23.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q23.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q23.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q23.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q24.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q24.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q24.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q24.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q24.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q24.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q24.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q25.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q25.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q25.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q25.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q25.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q25.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q25.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q26.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q26.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q26.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q26.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q26.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q26.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q26.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q27.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q27.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q27.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q27.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q27.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q27.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q27.id, scoring_value: 7, option_copy: "Very Much" )

@Q28 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "individualizing", question_copy: "Perceived Likelihood of Using" )
@Q29 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "individualizing", question_copy: "Willingness to Use" )
@Q30 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "individualizing", question_copy: "Perceived Difficulty")
@Q31 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "individualizing", question_copy: "Perceived Effectiveness" )
@Q32 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "individualizing", question_copy: "Perceived Frequency of Opportunity to Use" )

  Option.create!(question_id: @Q28.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q28.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q28.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q28.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q28.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q28.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q28.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q29.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q29.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q29.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q29.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q29.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q29.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q29.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q30.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q30.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q30.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q30.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q30.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q30.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q30.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q31.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q31.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q31.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q31.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q31.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q31.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q31.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q32.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q32.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q32.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q32.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q32.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q32.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q32.id, scoring_value: 7, option_copy: "Very Much" )

@Q33 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "perspective-taking", question_copy: "Perceived Likelihood of Using" )
@Q34 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "perspective-taking", question_copy: "Willingness to Use" )
@Q35 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "perspective-taking", question_copy: "Perceived Difficulty")
@Q36 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "perspective-taking", question_copy: "Perceived Effectiveness" )
@Q37 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "perspective-taking", question_copy: "Perceived Frequency of Opportunity to Use" )

  Option.create!(question_id: @Q33.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q33.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q33.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q33.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q33.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q33.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q33.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q34.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q34.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q34.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q34.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q34.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q34.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q34.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q35.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q35.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q35.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q35.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q35.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q35.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q35.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q36.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q36.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q36.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q36.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q36.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q36.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q36.id, scoring_value: 7, option_copy: "Very Much" )

  Option.create!(question_id: @Q37.id, scoring_value: 1, option_copy: "Not at All" )
  Option.create!(question_id: @Q37.id, scoring_value: 2, option_copy: "Rarely" )
  Option.create!(question_id: @Q37.id, scoring_value: 3, option_copy: "Occasionally" )
  Option.create!(question_id: @Q37.id, scoring_value: 4, option_copy: "Somtimes" )
  Option.create!(question_id: @Q37.id, scoring_value: 5, option_copy: "Frequently" )
  Option.create!(question_id: @Q37.id, scoring_value: 6, option_copy: "Usually" )
  Option.create!(question_id: @Q37.id, scoring_value: 7, option_copy: "Very Much" )

@Q38 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "contact", question_copy: "Perceived Likelihood of Using" )
@Q39 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "contact", question_copy: "Willingness to Use" )
@Q40 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "contact", question_copy: "Perceived Difficulty")
@Q41 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "contact", question_copy: "Perceived Effectiveness" )
@Q42 = Question.create!(survey_format_id: @SR_Questionnaire.id, question_format: "likert", question_category: "contact", question_copy: "Perceived Frequency of Opportunity to Use" )

Option.create!(question_id: @Q38.id, scoring_value: 1, option_copy: "Not at All" )
Option.create!(question_id: @Q38.id, scoring_value: 2, option_copy: "Rarely" )
Option.create!(question_id: @Q38.id, scoring_value: 3, option_copy: "Occasionally" )
Option.create!(question_id: @Q38.id, scoring_value: 4, option_copy: "Somtimes" )
Option.create!(question_id: @Q38.id, scoring_value: 5, option_copy: "Frequently" )
Option.create!(question_id: @Q38.id, scoring_value: 6, option_copy: "Usually" )
Option.create!(question_id: @Q38.id, scoring_value: 7, option_copy: "Very Much" )

Option.create!(question_id: @Q39.id, scoring_value: 1, option_copy: "Not at All" )
Option.create!(question_id: @Q39.id, scoring_value: 2, option_copy: "Rarely" )
Option.create!(question_id: @Q39.id, scoring_value: 3, option_copy: "Occasionally" )
Option.create!(question_id: @Q39.id, scoring_value: 4, option_copy: "Somtimes" )
Option.create!(question_id: @Q39.id, scoring_value: 5, option_copy: "Frequently" )
Option.create!(question_id: @Q39.id, scoring_value: 6, option_copy: "Usually" )
Option.create!(question_id: @Q39.id, scoring_value: 7, option_copy: "Very Much" )

Option.create!(question_id: @Q40.id, scoring_value: 1, option_copy: "Not at All" )
Option.create!(question_id: @Q40.id, scoring_value: 2, option_copy: "Rarely" )
Option.create!(question_id: @Q40.id, scoring_value: 3, option_copy: "Occasionally" )
Option.create!(question_id: @Q40.id, scoring_value: 4, option_copy: "Somtimes" )
Option.create!(question_id: @Q40.id, scoring_value: 5, option_copy: "Frequently" )
Option.create!(question_id: @Q40.id, scoring_value: 6, option_copy: "Usually" )
Option.create!(question_id: @Q40.id, scoring_value: 7, option_copy: "Very Much" )

Option.create!(question_id: @Q41.id, scoring_value: 1, option_copy: "Not at All" )
Option.create!(question_id: @Q41.id, scoring_value: 2, option_copy: "Rarely" )
Option.create!(question_id: @Q41.id, scoring_value: 3, option_copy: "Occasionally" )
Option.create!(question_id: @Q41.id, scoring_value: 4, option_copy: "Somtimes" )
Option.create!(question_id: @Q41.id, scoring_value: 5, option_copy: "Frequently" )
Option.create!(question_id: @Q41.id, scoring_value: 6, option_copy: "Usually" )
Option.create!(question_id: @Q41.id, scoring_value: 7, option_copy: "Very Much" )

Option.create!(question_id: @Q42.id, scoring_value: 1, option_copy: "Not at All" )
Option.create!(question_id: @Q42.id, scoring_value: 2, option_copy: "Rarely" )
Option.create!(question_id: @Q42.id, scoring_value: 3, option_copy: "Occasionally" )
Option.create!(question_id: @Q42.id, scoring_value: 4, option_copy: "Somtimes" )
Option.create!(question_id: @Q42.id, scoring_value: 5, option_copy: "Frequently" )
Option.create!(question_id: @Q42.id, scoring_value: 6, option_copy: "Usually" )
Option.create!(question_id: @Q42.id, scoring_value: 7, option_copy: "Very Much" )

puts "#{Question.count} questions created"
puts "#{Option.count} options created"